-- ============================================================
-- 073_catalogo_procedimientos_completo.sql
-- Carga el catálogo maestro completo desde data/quirofano_procedimientos.csv
-- en catalogo_procedimientos (la que usa el registro de procedimientos).
--
-- CONTEXTO
--   catalogo_procedimientos tenía 195 filas y ninguna con especialidad_ref.
--   El CSV maestro tiene 316 nombres únicos; 35 ya existían, así que se
--   insertan los %d restantes.
--
-- LIMPIEZA APLICADA AL GENERAR ESTE ARCHIVO
--   1. Se quita el prefijo "(VAC)" de 3 nombres: era markup de la hoja de
--      cálculo, no parte del procedimiento.
--   2. Se descartan 2 nombres repetidos en el CSV con especialidades
--      distintas, porque catalogo_procedimientos.nombre es UNIQUE:
--        - Amputación   (Cirugía / Traumatología)   -> se conserva Cirugía
--        - Circuncisión (Pediatría / Cirugía)       -> se conserva Pediatría
--   3. especialidad_ref se llena con el mapeo declarado en el propio CSV:
--      Cirugía->CIR, Traumatología->TRA, Pediatría->PED,
--      Ginecología->GIN, Medicina Interna->MI.
--
-- PENDIENTE DE REVISIÓN (del CSV de origen)
--   Estas 7 entradas del CSV no son procedimientos, sino diagnósticos,
--   complicaciones o indicaciones de manejo. Se insertaron porque pertenecen
--   al catálogo de origen, pero conviene revisarlas:
--     - Infección del tracto urinario (UTI)
--     - Infección en sitio quirúrgico
--     - Síndrome compartimental (fasciotomía)
--     - Manejo conservador
--     - Control de daños
--     - Control de hemorragias
--     - Dedo en gatillo
--
-- Es idempotente: se puede volver a aplicar sin duplicar.
-- abreviatura queda NULL en las filas nuevas: no se inventan códigos y la
-- columna es nullable. Los 195 registros previos siguen sin abreviatura
-- propia y sin especialidad_ref.
-- ============================================================

BEGIN;

INSERT INTO catalogo_procedimientos (abreviatura, nombre, descripcion, anestesia, especialidad_ref, activo)
VALUES
    (NULL, 'Cambio de terapia de presión negativa', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colocación de terapia de presión negativa', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Retiro de terapia de presión negativa', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Abdominoplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Adenoamigdalectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Adenoidectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Adhesiolisis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Amigdalectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Amputación de urgencia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Anastomosis intestinal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Angioplastia coronaria', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Angioplastía de acceso vascular para hemodiálisis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Apendicectomía pediátrica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Atresias intestinales', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Banding', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Biopsia cervical', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Biopsia excisional', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Biopsia incisional', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Biopsia quirúrgica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Biopsia renal abierta', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Biopsia renal percutánea', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Blefaroplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Broncoscopia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Bypass coronario', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Bypass femoropoplíteo', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Bypass gástrico', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cateterismo cardíaco', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cauterización', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cesárea de emergencia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cierre de herida', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cierre de ostomías', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Circuncisión', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Cirugía de aneurisma cerebral', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de aorta torácica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de catarata', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Hemiartroplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Cirugía de columna vertebral', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de diverticulitis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de hidrocele', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Catéter umbilical (arterial/venoso)', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Artrodesis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Cirugía de quistes hepáticos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de quistes sebáceos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de sarcomas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de tiroides', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de tumores cerebrales', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de varicocele', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía endoscópica nasal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía hepatobiliar', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía ortognática', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía paliativa oncológica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía pancreática', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía por prolapso genital', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Cirugía vascular periférica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cistolitotomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cistoscopia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colectomía oncológica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colgajo cutáneo', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colocación de arco de Erich', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colocación de catéter doble J', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colocación de catéter para diálisis peritoneal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colocación de catéter para hemodiálisis (temporal)', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colocación de catéter tunelizado para hemodiálisis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colocación de injerto arteriovenoso para diálisis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colonoscopia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Colporrafia posterior', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Conización cervical', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Control de daños', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Control de hemorragias', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Corrección de atresia intestinal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Artrocentesis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Antrodesis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Corrección de labio y paladar hendido', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'CPRE', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Craneotomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Craniectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Craniectomía descompresiva', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Creación de fístula arteriovenosa (braquiocefálica)', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Creación de fístula arteriovenosa (radiocefálica)', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cuadrantectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Debridamiento quirúrgico', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Debulking tumoral', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Decorticación pleural', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Decorticación pulmonar', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Decortificación de riñón', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Dedo en gatillo', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Derivación ventriculoperitoneal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Desbridamiento de tejidos infectados', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Discectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Disección axilar', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Disección cervical', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Drenaje biliar', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Drenaje de absceso renal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Drenaje de abscesos profundos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Drenaje epidural', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Drenaje torácico', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Embarazo ectópico', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Embolectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Endarterectomía carotídea', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Endoscopía + dilatación', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Endoscopia digestiva alta', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Endoscopía y toma de biopsia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Enterectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Esplenectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Estenosis pilórica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Estimulación cerebral profunda', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Evacuación de hematomas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Eventrorrafia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Extracción de cuerpos extraños', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Extracción de terceros molares', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Fasciotomía urgente', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Fenestración laparoscópica de quiste renal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Tratamiento quirúrgico de fractura expuesta', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Fístula arteriovenosa', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Fistulectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Fisurotomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Funduplicatura', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Fusión vertebral', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Gastrectomía oncológica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Gastrectomía subtotal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Gastrectomía total', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Gastroscopía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'MI'), TRUE),
    (NULL, 'Gastrostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Gastrostomía pediátrica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Hemicolectomía derecha', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Hemicolectomía izquierda', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Hepatectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Hernioplastía incisional', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Hernioplastía inguinal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Hernioplastía umbilical', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Herniorrafia inguinal pediátrica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Histerectomía abdominal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Histerectomía laparoscópica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Histerectomía quirúrgica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Ileostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Implantación de marcapasos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Infección del tracto urinario (UTI)', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Síndrome compartimental (fasciotomía)', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Invaginación intestinal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Laminectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Laparoscopía diagnóstica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Laparoscopía ginecológica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Laparotomía de urgencia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Laparotomía exploradora', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Laringectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'LASIK', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Lavado y desbridamiento', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Lavado y desbridamiento por quemadura', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Levantamiento óseo frontal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de tendones', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Ligadura de trompas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Ligadura tubárica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Linfadenectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Litotricia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Lobectomía pulmonar', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Malformaciones anorrectales', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Malformaciones congénitas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Mamoplastia reductora', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de ligamentos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Manejo de quemaduras', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Manejo quirúrgico de trauma abdominal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Manga gástrica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Marsupialización de quiste de Bartolino', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Marsupialización de quiste renal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Mastectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Mastoidectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Mediastinoscopia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reemplazo de rodilla', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Microlaringoscopía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefrectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefrectomía parcial', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefrectomía radical', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefrectomía simple', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefrolitotomía percutánea', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefrostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefrostomía percutánea', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Nefroureterectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Neumonectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reemplazo de cadera', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Reducción cerrada de fractura', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Osteotomía mandibular', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Otoplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Pancreatectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Pancreatectomía oncológica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Paratiroidectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Pericardiocentesis quirúrgica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Pieloplastía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Piloromiotomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'PED'), TRUE),
    (NULL, 'Piloroplastía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Pleurodesis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Polipectomía endoscópica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Polipectomía nasal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Queratoplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Quistectomía ovárica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Reconstrucción facial', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reconstrucción mamaria', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reconstrucción maxilar', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reducción abierta y fijación interna (RAFI)', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Osteostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Reducción de fractura facial', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Meniscectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Reemplazo valvular', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reexploración abdominal y cierre por planos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reimplante de uréter', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Remodelación de Colostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de aneurismas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de desgarros obstétricos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Reparación de desprendimiento de retina', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de fístula arteriovenosa', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de fractura facial', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de fracturas craneales', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de hernias', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de lesiones complejas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Manejo conservador', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Reparación de perforaciones gastrointestinales', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación de prolapso uterino', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Liberación del túnel carpiano', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Reparación valvular', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Reparación vascular', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección de lipomas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección de tejido', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección de tumor cerebral', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección de tumores', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección de tumores de piel y tejidos blandos', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección de tumores maxilares', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección de tumores mediastinales', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección hepática', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección intestinal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Resección transuretral de próstata', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Retiro de catéter para diálisis peritoneal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Retiro de catéter para hermodiálisis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Revisión o recambio de catéter peritoneal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Revisión quirúrgica de acceso vascular', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Rinoplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Salpingectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Salpingooforectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Septoplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Sigmoidectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Infección en sitio quirúrgico', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Sutura de heridas', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Fijador externo', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Timpanoplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Tiroidectomía oncológica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Tiroidectomía parcial', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Tiroidectomía total', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Toracotomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Toracotomía de emergencia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trabeculectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Transposición de vena basílica', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Traqueostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trasplante cardíaco', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trasplante de médula ósea', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trasplante hepático', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trasplante pancreático', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trasplante pulmonar', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trasplante renal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Tratamiento quirúrgico de endometriosis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Fijación percutánea', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Tratamiento quirúrgico del sangrado digestivo', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trombectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Trombectomía de fístula arteriovenosa', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Tumorectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Ureterolitotomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Ureteroscopia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Vagotomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Varicectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Varicocelectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Vitrectomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Yeyunostomía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Fijación externa', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Corrección de escoliosis', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Corrección de deformidades', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Cirugía de pie', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Biopsia Tru-Cut', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'CIR'), TRUE),
    (NULL, 'Cirugía de mano', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Cirugía de columna', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Artroscopía', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE),
    (NULL, 'Reparación de desgarro cervical/vaginal', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'GIN'), TRUE),
    (NULL, 'Artroplastia', NULL, 0, (SELECT id FROM especialidades WHERE abreviatura = 'TRA'), TRUE)

ON CONFLICT (nombre) DO NOTHING;

COMMIT;
