SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS parentescos;

DROP TABLE IF EXISTS pueblos;

DROP TABLE IF EXISTS idiomas;

DROP TABLE IF EXISTS nacionalidades;

DROP TABLE IF EXISTS depto_muni;

DROP TABLE IF EXISTS estados_civiles;

DROP TABLE IF EXISTS educacion;

DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS permisos;

DROP TABLE IF EXISTS tipos_parto;

DROP TABLE IF EXISTS clases_parto;

DROP TABLE IF EXISTS tipo_lesion;

DROP TABLE IF EXISTS especialidad;

DROP TABLE IF EXISTS grupo_edad;

DROP TABLE IF EXISTS servicios;

DROP TABLE IF EXISTS tipos_cita;

DROP TABLE IF EXISTS codigo_procedimientos;

DROP TABLE IF EXISTS estados_salud;

DROP TABLE IF EXISTS situaciones_salud;

DROP TABLE IF EXISTS lugares_referencia;

DROP TABLE IF EXISTS estadia_es;

DROP TABLE IF EXISTS servio_es;

DROP TABLE IF EXISTS tipo_consulta;

DROP TABLE IF EXISTS estudios;

DROP TABLE IF EXISTS estatus;

DROP TABLE IF EXISTS pacientes;

DROP TABLE IF EXISTS referencia_contacto;

DROP TABLE IF EXISTS contacto_paciente;

DROP TABLE IF EXISTS usuarios;

DROP TABLE IF EXISTS madres;

DROP TABLE IF EXISTS medicos;

DROP TABLE IF EXISTS recien_nacidos;

DROP TABLE IF EXISTS constancias_nacimiento;

DROP TABLE IF EXISTS expedientes;

DROP TABLE IF EXISTS consultas;

DROP TABLE IF EXISTS citas;

DROP TABLE IF EXISTS proce_medicos;

DROP TABLE IF EXISTS uisau;

DROP TABLE IF EXISTS cie10;

CREATE TABLE IF NOT EXISTS parentescos (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE pueblos (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE idiomas (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE nacionalidades (
    iso VARCHAR(3) PRIMARY KEY,
    nacionalidad VARCHAR(50) DEFAULT NULL,
    pais VARCHAR(50) DEFAULT NULL,
    cti INT(3) DEFAULT NULL,
    idioma VARCHAR(30) DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE depto_muni (
    codigo CHAR(4) PRIMARY KEY,
    departamento VARCHAR(100) NOT NULL,
    municipio VARCHAR(100) NOT NULL,
    lugar VARCHAR(255) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE estados_civiles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) UNIQUE NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE educacion (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nivel VARCHAR(50) UNIQUE NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT DEFAULT NULL,
    permisos VARCHAR(250) DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE permisos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE tipos_parto (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(50) DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE clases_parto (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(50) DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE tipo_lesion (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE especialidad (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    especialista VARCHAR(100) DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE grupo_edad (
    id INT AUTO_INCREMENT PRIMARY KEY,
    grupo VARCHAR(50) NOT NULL,
    edad_inicio INT NOT NULL,
    edad_fin INT,
    caracteristicas TEXT
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE servicios (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE tipos_cita (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255) DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE codigo_procedimientos (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    abreviatura VARCHAR(10) NOT NULL,
    procedimiento VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE estados_salud (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE situaciones_salud (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE lugares_referencia (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE estadia_es (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE servio_es (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE tipo_consulta (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE estudios (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

CREATE TABLE estatus (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;