CREATE TABLE union_old (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    expediente INT DEFAULT NULL,
    nombre VARCHAR(50) DEFAULT NULL,
    apellido VARCHAR(50) DEFAULT NULL,
    nombre_completo VARCHAR(150) DEFAULT NULL,
    sexo VARCHAR(2) DEFAULT NULL,
    dpi VARCHAR(20) DEFAULT NULL,
    nacimiento DATE DEFAULT NULL,
    direccion VARCHAR(100) DEFAULT NULL,
    telefono VARCHAR(50) DEFAULT NULL,
    responsable VARCHAR(50) DEFAULT NULL,
    parentesco VARCHAR(19) DEFAULT NULL,
    paciente_id VARCHAR(50) DEFAULT NULL,
    pasaporte VARCHAR(50) DEFAULT NULL,
    nacionalidad INT DEFAULT NULL,
    lugar_nacimiento VARCHAR(4) DEFAULT NULL,
    estado_civil INT DEFAULT NULL,
    educacion INT DEFAULT NULL,
    pueblo INT DEFAULT NULL,
    idioma INT DEFAULT NULL,
    ocupacion VARCHAR(50) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    padre VARCHAR(50) DEFAULT NULL,
    madre VARCHAR(50) DEFAULT NULL,
    dpi_responsable BIGINT DEFAULT NULL,
    telefono_responsable VARCHAR(18) DEFAULT NULL,
    estado VARCHAR(2) DEFAULT NULL,
    exp_madre VARCHAR(20) DEFAULT NULL,
    gemelo VARCHAR(2) DEFAULT NULL,
    conyugue VARCHAR(100) DEFAULT NULL,
    defuncion VARCHAR(10) DEFAULT NULL,
    exp_ref INT DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    created_at DATETIME DEFAULT NULL,
    created_by VARCHAR(11) DEFAULT NULL,
    consulta_id INT DEFAULT NULL,
    hoja_emergencia VARCHAR(15) DEFAULT NULL,
    fecha_consulta DATE DEFAULT NULL,
    hora TIME DEFAULT NULL,
    edad VARCHAR(200) DEFAULT NULL,
    nota TEXT NULL,
    especialidad INT DEFAULT NULL,
    servicio INT DEFAULT NULL,
    status INT DEFAULT NULL,
    egreso DATETIME DEFAULT NULL,
    recepcion DATETIME DEFAULT NULL,
    tipo_consulta INT DEFAULT NULL,
    prenatal INT DEFAULT NULL,
    lactancia VARCHAR(2) DEFAULT NULL,
    diagnostico VARCHAR(100) DEFAULT NULL,
    folios VARCHAR(25) DEFAULT NULL,
    medico VARCHAR(100) DEFAULT NULL,
    consulta_por INT DEFAULT NULL,
    archivado_por VARCHAR(10) DEFAULT NULL
) ENGINE = InnoDB CHARSET = utf8mb4;

SET @consulta_id = 1;

UPDATE union_old
SET
    consulta_id = (
        @consulta_id := @consulta_id + 1
    )
ORDER BY id;

CREATE TABLE xxx LIKE union_old;

CREATE TABLE old_pacientes AS
SELECT
    id,
    expediente,
    nombre,
    apellido,
    CONCAT_WS(' ', nombre, apellido) AS nombre_completo,
    sexo,
    dpi,
    nacimiento,
    direccion,
    telefono,
    responsable,
    parentesco,
    id AS paciente_id,
    pasaporte,
    nacionalidad,
    LPAD(
        CAST(lugar_nacimiento AS CHAR),
        4,
        '0'
    ) AS lugar_nacimiento,
    estado_civil,
    educacion,
    pueblo,
    idioma,
    ocupacion,
    email,
    padre,
    madre,
    dpi_responsable,
    telefono_responsable,
    estado,
    exp_madre,
    gemelo,
    conyugue,
    fechaDefuncion AS defuncion,
    exp_ref,
    update_at AS updated_at,
    created_at,
    created_by,
    NULL AS consulta_id,
    NULL AS hoja_emergencia,
    NULL AS fecha_consulta,
    NULL AS hora,
    NULL AS edad,
    NULL AS nota,
    NULL AS especialidad,
    NULL AS servicio,
    NULL AS status,
    NULL AS egreso,
    NULL AS recepcion,
    NULL AS tipo_consulta,
    NULL AS prenatal,
    NULL AS lactancia,
    NULL AS diagnostico,
    NULL AS folios,
    NULL AS medico,
    NULL AS consulta_por,
    NULL AS archivado_por
FROM pacientes;

ALTER TABLE old_pacientes ENGINE = InnoDB, DEFAULT CHARSET = utf8mb4;

CREATE TABLE old_consultas AS
SELECT
    id,
    expediente,
    nombres AS nombre,
    apellidos AS apellido,
    CONCAT_WS(' ', nombres, apellidos) AS nombre_completo,
    sexo,
    dpi,
    nacimiento,
    direccion,
    telefono,
    created_at,
    updated_at,
    acompa AS responsable,
    NULL AS parentesco,
    NULL AS paciente_id,
    NULL AS pasaporte,
    NULL AS nacionalidad,
    NULL AS lugar_nacimiento,
    NULL AS estado_civil,
    NULL AS educacion,
    NULL AS pueblo,
    NULL AS idioma,
    NULL AS ocupacion,
    NULL AS email,
    NULL AS padre,
    NULL AS madre,
    NULL AS dpi_responsable,
    NULL AS telefono_responsable,
    NULL AS estado,
    NULL AS exp_madre,
    NULL AS gemelo,
    NULL AS conyugue,
    NULL AS defuncion,
    NULL AS exp_ref,
    id AS consulta_id,
    hoja_emergencia,
    fecha_consulta,
    hora,
    edad,
    CONCAT_WS(' ', medico, nota) AS nota,
    especialidad,
    servicio,
    status,
    fecha_egreso AS egreso,
    fecha_recepcion AS recepcion,
    tipo_consulta,
    prenatal,
    lactancia,
    dx AS diagnostico,
    folios,
    NULL AS medico,
    created_by,
    consulta_por,
    archived_by AS archivado_por
FROM consultas;

DELETE FROM old_consultas WHERE nombre_completo LIKE '%anula%';

DELETE FROM old_consultas WHERE nombre_completo = '';

ALTER TABLE old_consultas ENGINE = InnoDB, DEFAULT CHARSET = utf8mb4;